name: Cypress Component Tests

# This workflow runs when a pull request is opened, synchronized, or reopened against the develop branch
on:
  pull_request:
    branches: [develop]
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci
      
      # Step 4: Run Cypress component tests
      - name: Run Cypress component tests
        uses: cypress-io/github-action@v5
        with:
          component: true
          
      # Step 5: Upload test results as artifacts
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-results
          path: |
            cypress/videos
            cypress/screenshots
          retention-days: 7