name: Cypress Component Tests

# This workflow runs when a pull request is opened, synchronized, or reopened against the develop branch
on:
  pull_request:
    branches: [develop]
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3

      
      # Step 3: Run Cypress component tests

      - name: Run Cypress component tests
        uses: cypress-io/github-action@v5
        with:
          component: true
          install: true
          build: npm run build
